"""
BAA 原子函数 - Structural Load
共 16 条原子函数，覆盖 GB50009 建筑结构荷载、GB55008 建筑与市政工程抗震、GB50010 混凝土结构设计。
"""

from ..atomic_functions import (
    AtomicFunction,
    FuncCategory,
)

MODULE_FUNCS = [
    # ── 楼面活荷载（GB50009-5.1 / GB55008）─────────────────
    AtomicFunction(
        "STR-001",
        "居住楼面活荷载判定",
        FuncCategory.STRUCTURAL,
        "GB50009-5.1.1",
        "住宅楼面活荷载标准值不应小于2.0 kN/㎡",
        ">=",
        2.0,
        "kN/㎡",
        target_entities=["floor", "slab"],
    ),
    AtomicFunction(
        "STR-002",
        "办公楼面活荷载判定",
        FuncCategory.STRUCTURAL,
        "GB50009-5.1.1",
        "办公楼面活荷载标准值不应小于2.5 kN/㎡",
        ">=",
        2.5,
        "kN/㎡",
        target_entities=["floor", "slab"],
    ),
    AtomicFunction(
        "STR-003",
        "商业楼面活荷载判定",
        FuncCategory.STRUCTURAL,
        "GB50009-5.1.1",
        "商店楼面活荷载标准值不应小于3.5 kN/㎡",
        ">=",
        3.5,
        "kN/㎡",
        target_entities=["floor", "slab"],
    ),
    AtomicFunction(
        "STR-004",
        "屋面活荷载判定",
        FuncCategory.STRUCTURAL,
        "GB50009-5.1.1",
        "不上人屋面活荷载不应小于0.5 kN/㎡；上人屋面不应小于2.0 kN/㎡",
        ">=",
        0.5,
        "kN/㎡",
        target_entities=["roof", "slab_top"],
    ),
    # ── 梁柱配筋率（GB50010）────────────────────────────
    AtomicFunction(
        "STR-005",
        "梁最小配筋率判定",
        FuncCategory.STRUCTURAL,
        "GB50010-9.2.1",
        "梁受拉纵筋最小配筋率不应小于0.2%和45ft/fy的较大值",
        ">=",
        0.2,
        "%",
        target_entities=["beam", "girder"],
    ),
    AtomicFunction(
        "STR-006",
        "柱纵向配筋率下限判定",
        FuncCategory.STRUCTURAL,
        "GB50010-11.4.12",
        "柱纵向钢筋最小配筋率不应小于0.55%（抗震一级）或0.50%（二级）",
        ">=",
        0.55,
        "%",
        target_entities=["column", "pillar"],
    ),
    AtomicFunction(
        "STR-007",
        "柱纵向配筋率上限判定",
        FuncCategory.STRUCTURAL,
        "GB50010-11.4.12",
        "柱纵向钢筋最大配筋率不应大于5.0%",
        "<=",
        5.0,
        "%",
        target_entities=["column", "pillar"],
    ),
    # ── 基础埋深（GB50007 / GB55008）────────────────────
    AtomicFunction(
        "STR-008",
        "基础最小埋深判定",
        FuncCategory.STRUCTURAL,
        "GB50007-5.1.3",
        "基础埋深不应小于0.5m（不考虑冻结深度）",
        ">=",
        0.5,
        "m",
        target_entities=["foundation", "footing", "pile"],
    ),
    AtomicFunction(
        "STR-009",
        "桩基础数量判定",
        FuncCategory.STRUCTURAL,
        "GB55008-4.1.1",
        "柱下独立桩基不少于2根；柱下条形桩基不少于3根",
        ">=",
        2.0,
        "个",
        target_entities=["pile", "pile_cap"],
    ),
    # ── 墙体/洞口（GB55008）────────────────────────────
    AtomicFunction(
        "STR-010",
        "剪力墙洞口面积比判定",
        FuncCategory.STRUCTURAL,
        "GB55008-4.3.1",
        "抗震墙中洞口的面积不宜大于该墙面积的50%",
        "<=",
        0.50,
        "",
        target_entities=["shear_wall", "wall"],
    ),
    AtomicFunction(
        "STR-011",
        "墙肢最小厚度判定",
        FuncCategory.STRUCTURAL,
        "GB55008-4.3.1",
        "剪力墙墙肢厚度不应小于160mm（框支层不应小于200mm）",
        ">=",
        160.0,
        "mm",
        target_entities=["shear_wall", "wall"],
    ),
    # ── 抗震设防（GB55008）────────────────────────────
    AtomicFunction(
        "STR-012",
        "抗震设防烈度判定",
        FuncCategory.STRUCTURAL,
        "GB55008-3.1.1",
        "抗震设防烈度不应低于6度（设计基本地震加速度≥0.05g）",
        ">=",
        6.0,
        "度",
        target_entities=["building", "structure"],
    ),
    AtomicFunction(
        "STR-013",
        "抗震等级存在判定",
        FuncCategory.STRUCTURAL,
        "GB55008-3.2.1",
        "抗震设计建筑应明确标注抗震等级",
        "==",
        1.0,
        "有/无",
        target_entities=["building", "structure"],
    ),
    # ── 混凝土强度（GB50010 / GB55008）─────────────────
    AtomicFunction(
        "STR-014",
        "混凝土最低强度等级判定",
        FuncCategory.STRUCTURAL,
        "GB50010-4.1.2",
        "混凝土结构最低强度等级不应低于C20（预应力不应低于C40）",
        ">=",
        20.0,
        "MPa",
        target_entities=["concrete", "slab", "beam", "column"],
    ),
    # ── 楼板厚度（GB50010 / GB50189）─────────────────
    AtomicFunction(
        "STR-015",
        "现浇楼板最小厚度判定",
        FuncCategory.STRUCTURAL,
        "GB50010-9.1.2",
        "现浇钢筋混凝土楼板厚度不应小于80mm（屋面板不应小于90mm）",
        ">=",
        80.0,
        "mm",
        target_entities=["slab", "floor"],
    ),
    AtomicFunction(
        "STR-016",
        "梁截面最小高度判定",
        FuncCategory.STRUCTURAL,
        "GB50010-9.2.3",
        "梁截面高度不宜小于跨度的1/12（简支）或1/15（连续）",
        ">=",
        0.0833,
        "",
        target_entities=["beam", "girder"],
    ),
]
