"""
BAA 原子函数 - Thermal
共 16 条原子函数，覆盖 GB50176 建筑热工设计 + GB50189 公共建筑节能 + GB55015 建筑节能与可再生能源利用通用规范。
"""

from ..atomic_functions import (
    AtomicFunction,
    FuncCategory,
)

MODULE_FUNCS = [
    # ── 传热系数 K 值（GB50176 / GB55015）─────────────────
    AtomicFunction(
        "THERM-001",
        "外墙传热系数判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区外墙K值不应大于0.45 W/(m²·K)；夏热冬冷地区不应大于1.5；夏热冬暖地区不应大于2.0",
        "<=",
        0.45,
        "W/(m²·K)",
        target_entities=["exterior_wall", "wall"],
    ),
    AtomicFunction(
        "THERM-002",
        "屋顶传热系数判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区屋顶K值不应大于0.35；夏热冬冷不应大于1.2；夏热冬暖不应大于1.5",
        "<=",
        0.35,
        "W/(m²·K)",
        target_entities=["roof", "slab_top"],
    ),
    AtomicFunction(
        "THERM-003",
        "地面传热系数判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区地面K值不应大于0.30",
        "<=",
        0.30,
        "W/(m²·K)",
        target_entities=["ground_floor", "floor"],
    ),
    AtomicFunction(
        "THERM-004",
        "外窗传热系数判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区外窗K值不应大于2.0；夏热冬冷不应大于3.2；夏热冬暖不应大于4.0",
        "<=",
        2.0,
        "W/(m²·K)",
        target_entities=["exterior_window", "window"],
    ),
    AtomicFunction(
        "THERM-005",
        "外窗玻璃传热系数判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区外窗玻璃K值不应大于2.4；夏热冬冷不应大于4.7",
        "<=",
        2.4,
        "W/(m²·K)",
        target_entities=["window_glass", "glazing"],
    ),
    # ── 遮阳系数 / 窗墙比（GB50189）─────────────────────
    AtomicFunction(
        "THERM-006",
        "外窗遮阳系数判定",
        FuncCategory.THERMAL,
        "GB50189-6.3.4",
        "夏热冬暖地区东西向外窗遮阳系数Sc不应大于0.35；南向外窗Sc不应大于0.40",
        "<=",
        0.35,
        "",
        target_entities=["exterior_window", "window", "shading"],
    ),
    AtomicFunction(
        "THERM-007",
        "窗墙面积比判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区各朝向窗墙比不应大于0.45；夏热冬冷不应大于0.40",
        "<=",
        0.45,
        "",
        target_entities=["wall", "exterior_wall", "facade"],
    ),
    # ── 保温层厚度（GB50176 / GB55015）───────────────────
    AtomicFunction(
        "THERM-008",
        "外墙保温层厚度判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区外墙保温层厚度不应小于50mm（具体按K值反算）",
        ">=",
        50.0,
        "mm",
        target_entities=["insulation", "exterior_wall"],
    ),
    AtomicFunction(
        "THERM-009",
        "屋顶保温层厚度判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区屋顶保温层厚度不应小于60mm（具体按K值反算）",
        ">=",
        60.0,
        "mm",
        target_entities=["insulation", "roof"],
    ),
    AtomicFunction(
        "THERM-010",
        "外窗保温层厚度判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区外窗保温层厚度不应小于30mm（具体按K值反算）",
        ">=",
        30.0,
        "mm",
        target_entities=["insulation", "window"],
    ),
    # ── 热桥 / 气密性（GB50176）────────────────────────
    AtomicFunction(
        "THERM-011",
        "热桥部位保温连续判定",
        FuncCategory.THERMAL,
        "GB50176-4.3.3",
        "外墙、屋顶与内墙、楼板连接处应采取保温连续措施消除热桥",
        "==",
        1.0,
        "有/无",
        target_entities=["thermal_bridge", "junction", "exterior_wall"],
    ),
    AtomicFunction(
        "THERM-012",
        "建筑外窗气密性等级判定",
        FuncCategory.THERMAL,
        "GB7106-5.1",
        "严寒寒冷地区外窗气密性等级不应低于6级；夏热冬冷不应低于4级",
        ">=",
        6.0,
        "级",
        target_entities=["exterior_window", "window"],
    ),
    # ── 窗墙比（存在性）─────────────────────────────
    AtomicFunction(
        "THERM-013",
        "外窗存在判定",
        FuncCategory.THERMAL,
        "GB50016-6.3.2",
        "建筑外墙应设置外窗",
        "==",
        1.0,
        "有/无",
        target_entities=["exterior_window", "window"],
    ),
    # ── 综合保温（面积比）─────────────────────────────
    AtomicFunction(
        "THERM-014",
        "外墙保温面积比判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区外墙保温面积比不应小于80%",
        ">=",
        0.80,
        "",
        target_entities=["exterior_wall", "insulation"],
    ),
    AtomicFunction(
        "THERM-015",
        "屋顶保温面积比判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区屋顶保温面积比不应小于90%",
        ">=",
        0.90,
        "",
        target_entities=["roof", "insulation"],
    ),
    AtomicFunction(
        "THERM-016",
        "外窗综合传热系数判定",
        FuncCategory.THERMAL,
        "GB55015-3.2.2",
        "严寒寒冷地区外窗综合传热系数不应大于3.0 W/(m²·K)",
        "<=",
        3.0,
        "W/(m²·K)",
        target_entities=["exterior_window", "window"],
    ),
]
