"""
BAA 原子函数 - AREA 类别
19 条原子函数
"""

from ...atomic_functions import (
    AtomicFunction,
    FuncCategory,
)

MODULE_FUNCS = [
AtomicFunction(
        "AREA-001",
        "避难层面积判定",
        FuncCategory.AREA,
        "GB50016-7.4.1",
        "避难层净面积不宜小于5㎡/人",
        ">=",
        5.0,
        "㎡/人",
        target_entities=["refuge_floor", "refuge_area", "floor"],
    ),
AtomicFunction(
        "AREA-002",
        "消防电梯前室面积判定",
        FuncCategory.AREA,
        "GB50016-7.3.5",
        "消防电梯前室面积不应小于6㎡",
        ">=",
        6.0,
        "㎡",
        target_entities=["elevator_lobby", "lobby"],
    ),
AtomicFunction(
        func_id="AREA-003",
        name="避难层净面积判定",
        description="避难层净面积按5.0人/sqm设计（GB50016-5.5.23）",
        category=FuncCategory.AREA,
        clause_id="GB50016-5.5.23",
        target_entities={"refuge_floor"},
        operator="ge",
        threshold=50.0,
        unit="sqm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-004",
        name="消防控制室面积判定",
        description="消防控制室面积不应小于30sqm（GB50016-8.1.7）",
        category=FuncCategory.AREA,
        clause_id="GB50016-8.1.7",
        target_entities={"control_room", "room"},
        operator="ge",
        threshold=30.0,
        unit="sqm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-005",
        name="柴油发电机房面积判定",
        description="柴油发电机房建筑面积不宜大于400m²（GB50016-5.4.15）",
        category=FuncCategory.AREA,
        clause_id="GB50016-5.4.15",
        target_entities={"generator_room", "room"},
        operator="le",
        threshold=400.0,
        unit="sqm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-007",
        name="手术室避难间面积判定",
        description="手术室避难间净面积不应小于25.0sqm（GB50016-5.5.24-3）",
        category=FuncCategory.AREA,
        clause_id="GB50016-5.5.24-3",
        target_entities={"operating_room", "surgery_room", "refuge_room"},
        operator="ge",
        threshold=25.0,
        unit="sqm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-009",
        name="避难层面积判定",
        description="避难层（间）净面积不应小于5人/㎡（GB50016-5.5.24）",
        category=FuncCategory.AREA,
        clause_id="GB50016-5.5.24",
        target_entities={"refuge_floor", "refuge_room"},
        operator=">=",
        threshold=5.0,
        unit="人/㎡",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-010",
        name="消防救援场地面积判定",
        description="消防救援场地长度不应小于15m，宽度不应小于10m（GB50016-7.2.1）",
        category=FuncCategory.AREA,
        clause_id="GB50016-7.2.1",
        target_entities={"rescue_ground", "rescue_area"},
        operator=">=",
        threshold=150.0,
        unit="㎡",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-011",
        name="自然排烟窗口面积判定",
        description="自然排烟窗口面积不应小于地面面积的2%（GB50016-8.2.3）",
        category=FuncCategory.AREA,
        clause_id="GB50016-8.2.3",
        target_entities={"smoke_vent", "window", "natural_vent"},
        operator="ge",
        threshold=0.02,
        unit="%",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-012",
        name="汽车库排烟量判定",
        description="汽车库排烟量不应小于30000m³/h（GB50067-8.2.2）",
        category=FuncCategory.AREA,
        clause_id="GB50067-8.2.2",
        target_entities={"smoke_exhaust", "smoke_vent", "fan"},
        operator=">=",
        threshold=30000.0,
        unit="m³/h",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-013",
        name="消防救援窗净面积判定",
        description="消防救援窗净面积不应小于1.0㎡，窗口下沿距室内地面不宜大于1.2m（GB50016-7.2.4-2）",
        category=FuncCategory.AREA,
        clause_id="GB50016-7.2.4-2",
        target_entities={"rescue_window", "window", "rescue_opening"},
        operator=">=",
        threshold=1.0,
        unit="㎡",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-014",
        name="消防救援场地最小宽度判定",
        description="消防救援场地宽度不应小于10m，长度不应小于15m（GB50016-7.2.1）",
        category=FuncCategory.AREA,
        clause_id="GB50016-7.2.1",
        target_entities={"rescue_area", "fire_platform", "rescue_ground"},
        operator=">=",
        threshold=150.0,
        unit="㎡",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-015",
        name="避难层人均面积判定",
        description="避难层净面积应按5.0人/㎡计算，净面积不应小于50㎡（GB50016-7.4.1）",
        category=FuncCategory.AREA,
        clause_id="GB50016-7.4.1",
        target_entities={"refuge_floor", "refuge_area", "refuge_room"},
        operator=">=",
        threshold=50.0,
        unit="㎡",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-016",
        name="消防控制室最小面积判定",
        description="消防控制室面积不应小于20㎡（GB50016-8.1.7）",
        category=FuncCategory.AREA,
        clause_id="GB50016-8.1.7",
        target_entities={"control_room", "fire_control_room", "room"},
        operator=">=",
        threshold=20.0,
        unit="㎡",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-017",
        name="自然排烟窗面积比判定",
        description="自然排烟窗（口）面积不应小于该场所地面面积的2%（GB50016-9.2.1）",
        category=FuncCategory.AREA,
        clause_id="GB50016-9.2.1",
        target_entities={"smoke_vent", "window", "smoke_window", "natural_vent"},
        operator=">=",
        threshold=0.02,
        unit="%",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-018",
        name="防烟楼梯间前室面积判定",
        description="公共建筑防烟楼梯间前室面积≥4.5m²，高层≥6.0m²（GB50016-6.4.3）",
        category=FuncCategory.AREA,
        clause_id="GB50016-6.4.3",
        target_entities={"antechamber", "staircase_lobby", "smoke_proof_lobby"},
        operator=">=",
        threshold=4.5,
        unit="m²",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-019",
        name="消防电梯前室面积判定",
        description="消防电梯前室面积不应小于6.0m²（GB50016-7.3.2）",
        category=FuncCategory.AREA,
        clause_id="GB50016-7.3.2",
        target_entities={"fire_elevator_lobby", "elevator_lobby", "antechamber", "fire_elevator"},
        operator=">=",
        threshold=6.0,
        unit="m²",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-020",
        name="避难层面积比判定",
        description="避难层(间)面积按5.0人/m²计算（GB50016-5.5.23）",
        category=FuncCategory.AREA,
        clause_id="GB50016-5.5.23",
        target_entities={"refuge_floor", "refuge_area", "room", "shelter"},
        operator=">=",
        threshold=5.0,
        unit="人/m²",
        depends_on=[],
    ),
AtomicFunction(
        func_id="AREA-021",
        name="剪刀楼梯间前室面积判定",
        description="剪刀楼梯间前室面积不应小于6.0m²（GB50016-5.5.24）",
        category=FuncCategory.AREA,
        clause_id="GB50016-5.5.24",
        target_entities={"antechamber", "staircase_lobby", "scissor_stair_lobby"},
        operator=">=",
        threshold=6.0,
        unit="m²",
        depends_on=[],
    ),
]
