"""
BAA 原子函数 - COUNT 类别
17 条原子函数
"""

from ...atomic_functions import (
    AtomicFunction,
    FuncCategory,
)

MODULE_FUNCS = [
AtomicFunction(
        "COUNT-001",
        "安全出口数量判定",
        FuncCategory.COUNT,
        "GB50016-5.5.8",
        "安全出口不应少于2个",
        ">=",
        2.0,
        "个",
        target_entities=["floor", "fire_zone"],
    ),
AtomicFunction(
        func_id="COUNT-002",
        name="高层建筑避难层数量判定",
        description="建筑高度大于100m时每50m应设一个避难层（GB50016-5.5.23）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.23",
        target_entities={"refuge_floor", "floor"},
        operator="ge",
        threshold=1.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-003",
        name="封闭楼梯间数量判定",
        description="建筑高度不大于21m的住宅建筑可采用敞开楼梯间（GB50016-5.5.25）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.25",
        target_entities={"staircase", "stair"},
        operator="ge",
        threshold=1.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-004",
        name="柴油发电机储油量判定",
        description="柴油发电机房储油间储油量不应大于1m³（GB50016-5.4.15）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.4.15",
        target_entities={"generator_room", "oil_room", "room"},
        operator="le",
        threshold=1.0,
        unit="m3",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-013",
        name="汽车库疏散出口数量判定",
        description="汽车库每个防火分区安全出口不应少于2个（GB50067-6.0.2）",
        category=FuncCategory.COUNT,
        clause_id="GB50067-6.0.2",
        target_entities={"exit", "door", "fire_door", "garage"},
        operator="ge",
        threshold=2,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-014",
        name="消防电梯数量判定",
        description="高层民用建筑每个防火分区消防电梯不应少于1台（GB50016-7.3.2）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-7.3.2",
        target_entities={"fire_elevator"},
        operator="ge",
        threshold=1,
        unit="台",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-015",
        name="疏散楼梯数量判定",
        description="公共建筑每个防火分区安全出口不应少于2个（GB50016-5.5.8）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.8",
        target_entities={"staircase", "exit", "safety_exit"},
        operator="ge",
        threshold=2,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-016",
        name="房间疏散门数量判定",
        description="公共建筑内每个房间疏散门不应少于2个（GB50016-5.5.15）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.15",
        target_entities={"room", "public_room"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-017",
        name="住宅安全出口数量判定",
        description="住宅建筑每个单元安全出口不应少于2个（GB50016-5.5.29）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.29",
        target_entities={"floor", "residential_unit", "fire_zone"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-019",
        name="防火分区安全出口数量判定",
        description="公共建筑每个防火分区安全出口不应少于2个（GB50016-5.5.8）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.8",
        target_entities={"exit", "exit_door", "fire_compartment", "room"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-020",
        name="大房间疏散门数量判定",
        description="面积大于50㎡的房间疏散门数量不应少于2个（GB50016-5.5.15）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.15",
        target_entities={"room", "hall", "auditorium", "classroom"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-021",
        name="住宅单元每层安全出口数量判定",
        description="住宅建筑每个单元每层安全出口不应少于2个（GB50016-5.5.25）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.25",
        target_entities={"exit", "exit_door", "staircase", "stair"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-022",
        name="18层以上住宅安全出口数量判定",
        description="18层以上住宅建筑每个单元每层安全出口不应少于2个（GB50016-5.5.29）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.29",
        target_entities={"exit", "exit_door", "staircase", "stair"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-023",
        name="防火分区消防电梯数量判定",
        description="每个防火分区消防电梯数量不应少于1台（GB50016-7.3.2）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-7.3.2",
        target_entities={"fire_elevator", "elevator", "lift"},
        operator=">=",
        threshold=1.0,
        unit="台",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-024",
        name="高层住宅安全出口数量判定",
        description="高层住宅建筑每个单元安全出口不应少于2个（GB50016-5.5.26）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.26",
        target_entities={"exit", "safety_exit", "door", "staircase"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-025",
        name="公共建筑安全出口数量判定",
        description="公共建筑每个防火分区安全出口不应少于2个（GB50016-5.5.15）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.15",
        target_entities={"exit", "safety_exit", "door", "fire_zone"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
AtomicFunction(
        func_id="COUNT-026",
        name="房间疏散门数量判定",
        description="建筑面积大于50m²的房间应设不少于2个疏散门（GB50016-5.5.16）",
        category=FuncCategory.COUNT,
        clause_id="GB50016-5.5.16",
        target_entities={"door", "room_door", "exit_door", "evacuation_door"},
        operator=">=",
        threshold=2.0,
        unit="个",
        depends_on=[],
    ),
]
