"""
BAA 原子函数 - DIST 类别
19 条原子函数
"""

from ...atomic_functions import (
    AtomicFunction,
    FuncCategory,
)

MODULE_FUNCS = [
AtomicFunction(
        "DIST-001",
        "疏散距离判定",
        FuncCategory.DISTANCE,
        "GB50016-5.5.17",
        "疏散距离不应大于30m",
        "<=",
        30.0,
        "m",
        target_entities=["room", "space"],  # P71 修复: 去掉 floor（楼板尺寸≠疏散距离）
    ),
AtomicFunction(
        "DIST-002",
        "防火间距判定",
        FuncCategory.DISTANCE,
        "GB50016-3.4.1",
        "厂房之间防火间距不应小于表3.4.1规定",
        ">=",
        12.0,
        "m",
        target_entities=["building", "factory", "warehouse"],
    ),
AtomicFunction(
        "DIST-003",
        "袋形走道长度判定",
        FuncCategory.DISTANCE,
        "GB50016-5.5.17",
        "袋形走道长度不应大于20m",
        "<=",
        20.0,
        "m",
        target_entities=["corridor", "aisle", "passage"],
    ),
AtomicFunction(
        "DIST-004",
        "救援窗口间距判定",
        FuncCategory.DISTANCE,
        "GB50016-7.2.5",
        "消防救援窗口间距不应大于20m",
        "<=",
        20.0,
        "m",
        target_entities=["rescue_window", "window"],
    ),
AtomicFunction(
        func_id="DIST-005",
        name="两个安全出口间距判定",
        description="两个安全出口之间的间距不应小于5.0m（GB50016-5.5.2）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-5.5.2",
        target_entities={"exit", "fire_door"},
        operator="ge",
        threshold=5000.0,
        unit="mm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-006",
        name="排烟口与安全出口间距判定",
        description="排烟口与安全出口之间的距离不应小于1.5m（GB50016-9.2.3）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-9.2.3",
        target_entities={"smoke_vent", "exit", "fire_door"},
        operator="ge",
        threshold=1500.0,
        unit="mm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-007",
        name="消防水源间距判定",
        description="室外消火栓间距不应大于120m（GB50016-8.1.3）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-8.1.3",
        target_entities={"hydrant", "fire_hydrant"},
        operator="le",
        threshold=120000.0,
        unit="mm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-008",
        name="防火分区安全出口间距判定",
        description="同一防火分区两个安全出口间距不应小于5m（GB50016-5.5.2）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-5.5.2",
        target_entities={"exit", "fire_door", "fire_zone"},
        operator="ge",
        threshold=5000.0,
        unit="mm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-009",
        name="高层建筑消防登高场地间距判定",
        description="高层建筑消防登高操作场地间隔不应大于30m（GB50016-7.2.2）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-7.2.2",
        target_entities={"rescue_area", "road", "driveway"},
        operator="le",
        threshold=30000.0,
        unit="mm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-010",
        name="室外消火栓保护半径判定",
        description="室外消火栓保护半径不应大于150m（GB50016-8.1.3）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-8.1.3",
        target_entities={"hydrant", "fire_hydrant"},
        operator="le",
        threshold=150000.0,
        unit="mm",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-016",
        name="防火卷帘与可燃物距离判定",
        description="防火卷帘两侧各0.5m范围内不应有可燃物（GB50016-6.5.3）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-6.5.3",
        target_entities={"fire_curtain", "curtain", "combustible", "material"},
        operator="ge",
        threshold=0.5,
        unit="m",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-020",
        name="汽车库疏散距离判定",
        description="汽车库内最远点到疏散出口距离不应大于45m（GB50067-6.0.5）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50067-6.0.5",
        target_entities={"room", "parking_space", "car"},
        operator="le",
        threshold=45.0,
        unit="m",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-021",
        name="汽车库与相邻建筑防火间距判定",
        description="汽车库与相邻建筑的防火间距不应小于10m（GB50067-4.2.1）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50067-4.2.1",
        target_entities={"building", "garage", "parking_lot"},
        operator="ge",
        threshold=10.0,
        unit="m",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-024",
        name="疏散距离判定（耐火等级二级）",
        description="一、二级耐火等级建筑内疏散距离不应大于40m（GB50016-5.5.12）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-5.5.12",
        target_entities={"room", "floor", "space"},
        operator="<=",
        threshold=40.0,
        unit="m",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-028",
        name="双向疏散距离判定",
        description="位于两个安全出口之间的房间，疏散距离不应大于40m（GB50016-5.5.17）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-5.5.17",
        target_entities={"room", "space", "office"},
        operator="<=",
        threshold=40.0,
        unit="m",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-029",
        name="高层建筑防火间距判定",
        description="高层民用建筑之间的防火间距不应小于13m（GB50016-3.4.1）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-3.4.1",
        target_entities={"building", "structure", "block"},
        operator=">=",
        threshold=13.0,
        unit="m",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-030",
        name="排烟口与安全出口间距判定",
        description="排烟口与安全出口（疏散门）的间距不应小于1.5m（GB50016-9.2.3）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-9.2.3",
        target_entities={"smoke_vent", "smoke_exhaust", "vent", "exit_door", "exit"},
        operator=">=",
        threshold=1.5,
        unit="m",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-022",
        name="疏散指示标志间距判定",
        description="疏散指示标志间距不应大于20m，袋形走道≤10m（GB50016-10.3.2）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-10.3.2",
        target_entities={"evacuation_sign", "exit_sign", "sign", "directional_sign"},
        operator="<=",
        threshold=20.0,
        unit="m",
        depends_on=[],
    ),
AtomicFunction(
        func_id="DIST-023",
        name="剪刀楼梯间间距判定",
        description="剪刀楼梯间间距不应小于4.0m（GB50016-5.5.25）",
        category=FuncCategory.DISTANCE,
        clause_id="GB50016-5.5.25",
        target_entities={"staircase", "scissor_stair", "stair"},
        operator=">=",
        threshold=4.0,
        unit="m",
        depends_on=[],
    ),
]
