"""
BAA 原子函数 - LIGHT 类别
10 条原子函数
"""

from ...atomic_functions import (
    AtomicFunction,
    FuncCategory,
)

MODULE_FUNCS = [
    AtomicFunction(
        "LIGHT-001",
        "应急照明照度判定",
        FuncCategory.DIMENSION,
        "GB50016-10.1.5",
        "疏散照明照度不应低于1.0lx",
        ">=",
        1.0,
        "lx",
        target_entities=["evacuation_lighting", "light", "lighting"],
    ),
    AtomicFunction(
        "LIGHT-002",
        "楼梯间应急照明照度判定",
        FuncCategory.DIMENSION,
        "GB50016-10.3.2",
        "楼梯间、前室等疏散照明照度不应低于5.0lx",
        ">=",
        5.0,
        "lx",
        target_entities=["staircase", "stair", "lobby", "corridor"],
    ),
    AtomicFunction(
        func_id="LIGHT-003",
        name="消防控制室应急照明照度判定",
        description="消防控制室、消防水泵房等应保持正常照明照度（GB50016-10.3.3）",
        category=FuncCategory.DIMENSION,
        clause_id="GB50016-10.3.3",
        target_entities={"control_room", "pump_room", "equipment_room"},
        operator="ge",
        threshold=100.0,
        unit="lx",
        depends_on=[],
    ),
    AtomicFunction(
        func_id="LIGHT-004",
        name="疏散走道疏散照明照度判定",
        description="疏散走道疏散照明地面最低照度不应低于1.0lx（GB50016-10.3.2）",
        category=FuncCategory.DIMENSION,
        clause_id="GB50016-10.3.2",
        target_entities={"corridor", "aisle", "passage"},
        operator="ge",
        threshold=1.0,
        unit="lx",
        depends_on=[],
    ),
    AtomicFunction(
        func_id="LIGHT-005",
        name="避难层应急照明照度判定",
        description="避难层应急照明照度不应低于3.0lx（GB50016-10.3.2）",
        category=FuncCategory.DIMENSION,
        clause_id="GB50016-10.3.2",
        target_entities={"refuge_floor", "refuge_area", "floor"},
        operator="ge",
        threshold=3.0,
        unit="lx",
        depends_on=[],
    ),
    AtomicFunction(
        func_id="LIGHT-006",
        name="应急照明灯具设置判定",
        description="封闭楼梯间、防烟楼梯间应设应急照明（GB50016-10.3.1）",
        category=FuncCategory.DIMENSION,
        clause_id="GB50016-10.3.1",
        target_entities={"emergency_lighting", "emergency_light"},
        operator="ge",
        threshold=1,
        unit="盏",
        depends_on=[],
    ),
    AtomicFunction(
        func_id="LIGHT-007",
        name="楼梯间应急照明照度判定",
        description="楼梯间、前室应急照明照度不应低于5.0lx（GB50016-10.1.5）",
        category=FuncCategory.LIGHT,
        clause_id="GB50016-10.1.5",
        target_entities={"staircase", "stair", "antechamber", "staircase_lobby"},
        operator=">=",
        threshold=5.0,
        unit="lx",
        depends_on=[],
    ),
    AtomicFunction(
        func_id="LIGHT-008",
        name="消防水泵房应急照明照度判定",
        description="消防水泵房、配电室等设备用房应急照明照度不应低于1.0lx（GB50016-10.3.3）",
        category=FuncCategory.LIGHT,
        clause_id="GB50016-10.3.3",
        target_entities={"pump_room", "control_room", "electrical_room", "equipment_room"},
        operator=">=",
        threshold=1.0,
        unit="lx",
        depends_on=[],
    ),
    AtomicFunction(
        func_id="LIGHT-009",
        name="疏散走道照度判定",
        description="疏散走道地面最低水平照度不应低于1.0lx（GB50016-10.1.5）",
        category=FuncCategory.LIGHT,
        clause_id="GB50016-10.1.5",
        target_entities={"corridor", "passageway", "evacuation_route", "walkway"},
        operator=">=",
        threshold=1.0,
        unit="lx",
        depends_on=[],
    ),
    AtomicFunction(
        func_id="LIGHT-010",
        name="设备用房应急照明照度判定",
        description="消防水泵房、配电室等设备用房应急照明照度≥1.0lx（GB50016-10.3.3）",
        category=FuncCategory.LIGHT,
        clause_id="GB50016-10.3.3",
        target_entities={"pump_room", "electrical_room", "control_room", "equipment_room"},
        operator=">=",
        threshold=1.0,
        unit="lx",
        depends_on=[],
    ),
]
