"""
BAA 多语言支持模块 (i18n)
============================
提供中文/英文/日文/韩文四种语言的字符串翻译和报告模板。

设计原则：
1. 扁平键值表：使用点号分隔的键（如 "report.title"）
2. 懒加载：按需加载语言包，不增加启动时间
3. 回退机制：缺失的翻译键回退到中文
4. 兼容扩展：新语言只需添加一个字典
"""

from typing import Dict, Optional

# ── 支持的语言代码 ─────────────────────────────────────
SUPPORTED_LANGUAGES = {
    "zh": "中文",
    "en": "English",
    "ja": "日本語",
    "ko": "한국어",
}

DEFAULT_LANGUAGE = "zh"  # 默认中文


# ══════════════════════════════════════════════════════════
# 翻译表
# ══════════════════════════════════════════════════════════

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "zh": {
        # ── 通用 ──
        "common.app_name": "BAA · Blueprint AI Agent",
        "common.disclaimer": "本报告由 BAA（Blueprint AI Agent）自动生成，仅供参考。",
        "common.generated_at": "生成日期",
        "common.building_type": "建筑类型",
        "common.civil": "民用建筑",
        "common.industrial": "工业建筑",
        "common.filename": "图纸文件",
        "common.total": "总计",
        "common.none": "无",
        "common.unknown": "未知",
        "common.by_type": "按严重级别",
        # ── 报告标题 ──
        "report.title": "图纸合规审查报告",
        "report.summary_title": "审查统计摘要",
        "report.violation_title": "违规详情",
        "report.correction_title": "修正建议",
        "report.correction_count": "共 {count} 条修正建议",
        # ── 统计卡片 ──
        "stat.violations": "违规总数",
        "stat.entities": "检查图元",
        "stat.checks": "检查项次",
        "stat.clauses": "涉及条款",
        # ── 表格头 ──
        "table.clause_id": "条款编号",
        "table.clause_name": "条款名称",
        "table.violation_count": "违规数",
        "table.entity_type": "实体类型",
        "table.quantity": "数量",
        # ── 违规详情 ──
        "violation.non_compliant": "❌ 不合规",
        "violation.warning": "⚠️ 警告",
        "violation.actual": "实际值",
        "violation.required": "要求值",
        "violation.difference": "偏差",
        "violation.explanation": "说明",
        "violation.suggestion": "💡 建议",
        # ── 摘要表 ──
        "summary.processing_time": "审查耗时",
        "summary.violation_by_clause": "违规按条款分布",
        "summary.entity_distribution": "实体类型分布",
        # ── 封面 ──
        "cover.score": "项目总体评分",
        "cover.compliance_rate": "合规率",
        "cover.files": "文件数",
        "cover.successful": "成功",
        "cover.failed": "失败",
        # ── 错误信息 ──
        "error.no_font": "未找到 CJK 字体文件 {path}。请安装 WenQuanYi 或设置 BAA_PDF_FONT 环境变量。",
        "error.language_not_supported": "不支持的语言：{lang}",
    },
    "en": {
        "common.app_name": "BAA · Blueprint AI Agent",
        "common.disclaimer": "This report is auto-generated by BAA (Blueprint AI Agent) for reference only.",
        "common.generated_at": "Generated At",
        "common.building_type": "Building Type",
        "common.civil": "Civil Building",
        "common.industrial": "Industrial Building",
        "common.filename": "Drawing File",
        "common.total": "Total",
        "common.none": "None",
        "common.unknown": "Unknown",
        "common.by_type": "By Severity",
        "report.title": "Drawing Compliance Review Report",
        "report.summary_title": "Review Summary",
        "report.violation_title": "Violation Details",
        "report.correction_title": "Correction Suggestions",
        "report.correction_count": "{count} correction suggestion(s)",
        "stat.violations": "Total Violations",
        "stat.entities": "Entities Checked",
        "stat.checks": "Checks Performed",
        "stat.clauses": "Clauses Involved",
        "table.clause_id": "Clause ID",
        "table.clause_name": "Clause Title",
        "table.violation_count": "Violations",
        "table.entity_type": "Entity Type",
        "table.quantity": "Quantity",
        "violation.non_compliant": "❌ Non-Compliant",
        "violation.warning": "⚠️ Warning",
        "violation.actual": "Actual",
        "violation.required": "Required",
        "violation.difference": "Difference",
        "violation.explanation": "Explanation",
        "violation.suggestion": "💡 Suggestion",
        "summary.processing_time": "Processing Time",
        "summary.violation_by_clause": "Violations by Clause",
        "summary.entity_distribution": "Entity Distribution",
        "cover.score": "Overall Score",
        "cover.compliance_rate": "Compliance Rate",
        "cover.files": "Files",
        "cover.successful": "Success",
        "cover.failed": "Failed",
        "error.no_font": "CJK font not found at {path}. Install WenQuanYi or set BAA_PDF_FONT env var.",
        "error.language_not_supported": "Unsupported language: {lang}",
    },
    "ja": {
        "common.app_name": "BAA · Blueprint AI Agent",
        "common.disclaimer": "このレポートはBAA（Blueprint AI Agent）によって自動生成されました。参考目的のみです。",
        "common.generated_at": "生成日",
        "common.building_type": "建築種別",
        "common.civil": "民用建築",
        "common.industrial": "産業建築",
        "common.filename": "図面ファイル",
        "common.total": "合計",
        "common.none": "なし",
        "common.unknown": "不明",
        "common.by_type": "重大別",
        "report.title": "図面コンプライアンス審査報告書",
        "report.summary_title": "審査サマリー",
        "report.violation_title": "違反詳細",
        "report.correction_title": "修正提案",
        "report.correction_count": "全 {count} 件の修正提案",
        "stat.violations": "違反総数",
        "stat.entities": "検査エンティティ",
        "stat.checks": "検査項目",
        "stat.clauses": "関連条項",
        "table.clause_id": "条項番号",
        "table.clause_name": "条項名",
        "table.violation_count": "違反数",
        "table.entity_type": "エンティティ種別",
        "table.quantity": "数量",
        "violation.non_compliant": "❌ 不適合",
        "violation.warning": "⚠️ 警告",
        "violation.actual": "実測値",
        "violation.required": "要求値",
        "violation.difference": "差異",
        "violation.explanation": "説明",
        "violation.suggestion": "💡 提案",
        "summary.processing_time": "処理時間",
        "summary.violation_by_clause": "条項別違反",
        "summary.entity_distribution": "エンティティ分布",
        "cover.score": "総合評価",
        "cover.compliance_rate": "コンプライアンス率",
        "cover.files": "ファイル数",
        "cover.successful": "成功",
        "cover.failed": "失敗",
        "error.no_font": "CJKフォントが見つかりません: {path}",
        "error.language_not_supported": "未対応の言語: {lang}",
    },
    "ko": {
        "common.app_name": "BAA · Blueprint AI Agent",
        "common.disclaimer": "이 보고서는 BAA(Blueprint AI Agent)에 의해 자동 생성되었습니다. 참고용입니다.",
        "common.generated_at": "생성일",
        "common.building_type": "건축 유형",
        "common.civil": "민간 건축",
        "common.industrial": "산업 건축",
        "common.filename": "도면 파일",
        "common.total": "합계",
        "common.none": "없음",
        "common.unknown": "알 수 없음",
        "common.by_type": "중요도별",
        "report.title": "도면 컴플라이언스 검토 보고서",
        "report.summary_title": "검토 요약",
        "report.violation_title": "위반 상세",
        "report.correction_title": "수정 제안",
        "report.correction_count": "총 {count}개의 수정 제안",
        "stat.violations": "위반 총계",
        "stat.entities": "검사 엔티티",
        "stat.checks": "검사 항목",
        "stat.clauses": "관련 조항",
        "table.clause_id": "조항 번호",
        "table.clause_name": "조항명",
        "table.violation_count": "위반 수",
        "table.entity_type": "엔티티 유형",
        "table.quantity": "수량",
        "violation.non_compliant": "❌ 부적합",
        "violation.warning": "⚠️ 경고",
        "violation.actual": "실측값",
        "violation.required": "요구값",
        "violation.difference": "차이",
        "violation.explanation": "설명",
        "violation.suggestion": "💡 제안",
        "summary.processing_time": "처리 시간",
        "summary.violation_by_clause": "조항별 위반",
        "summary.entity_distribution": "엔티티 분포",
        "cover.score": "종합 평가",
        "cover.compliance_rate": "컴플라이언스율",
        "cover.files": "파일 수",
        "cover.successful": "성공",
        "cover.failed": "실패",
        "error.no_font": "CJK 글꼴을 찾을 수 없음: {path}",
        "error.language_not_supported": "지원되지 않는 언어: {lang}",
    },
}


# ══════════════════════════════════════════════════════════
# 翻译函数
# ══════════════════════════════════════════════════════════


def t(key: str, lang: str = DEFAULT_LANGUAGE, **kwargs) -> str:
    """翻译指定语言的字符串

    参数:
        key: 翻译键，如 "report.title"
        lang: 语言代码，如 "zh", "en", "ja", "ko"
        **kwargs: 格式化参数，如 count=5 → "{count} 条" → "5 条"

    返回:
        翻译后的字符串，缺失键回退到中文
    """
    # 获取目标语言翻译，缺失时回退到中文
    lang_table = TRANSLATIONS.get(lang, TRANSLATIONS[DEFAULT_LANGUAGE])
    text = lang_table.get(key)

    if text is None:
        # 回退到中文
        zh_table = TRANSLATIONS[DEFAULT_LANGUAGE]
        text = zh_table.get(key, key)

    # 格式化参数
    if kwargs:
        try:
            text = text.format(**kwargs)
        except KeyError:
            pass

    return text


def supported_languages() -> Dict[str, str]:
    """获取支持的语言列表

    返回: {代码: 显示名}
    """
    return dict(SUPPORTED_LANGUAGES)


def is_supported(lang: str) -> bool:
    """检查语言是否受支持"""
    return lang in TRANSLATIONS
